# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-Oracle
version:      1.24
version_from: Oracle.pm
installdirs:  site
requires:
    DBI:                           1.51

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
