---
abstract: 'Oracle database driver for the DBI module'
author:
  - 'Tim Bunce <timb@cpan.org>'
  - 'John Scoles'
  - 'Yanick Champoux <yanick@cpan.org>'
  - 'Martin J. Evans <mjevans@cpan.org>'
build_requires:
  Carp: 0
  Config: 0
  Data::Dumper: 0
  Devel::Peek: 0
  Encode: 0
  Math::BigInt: 0
  Test::More: 0.88
  Thread::Semaphore: 0
  utf8: 0
  vars: 0
configure_requires:
  DBI: 1.51
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300027, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBD-Oracle
provides:
  DBD::Oracle:
    file: lib/DBD/Oracle.pm
    version: 1.53_00
  DBD::Oracle::GetInfo:
    file: lib/DBD/Oracle/GetInfo.pm
    version: 1.53_00
  DBD::Oracle::Object:
    file: lib/DBD/Oracle/Object.pm
    version: 1.53_00
requires:
  DBI: 0
  DynaLoader: 0
  Exporter: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-Oracle
  homepage: http://search.cpan.org/dist/DBD-Oracle/
  repository: https://github.com/yanick/DBD-Oracle.git
version: 1.53_00
x_authority: cpan:PYTHIAN
x_help_wanted:
  - coder
  - documentation
  - tester
