$dbd_oracle_mm_opts = {
                        'NAME' => 'DBD::Oracle',
                        'INC' => '-IC:/oracle/ora92/oci/include -IC:/oracle/ora92/rdbms/demo -IC:/Perl/site/lib/auto/DBI/',
                        'LIBS' => [
                                    '-LC:/oracle/ora92/oci/LIB/MSVC OCI'
                                  ],
                        'AUTHOR' => 'Tim Bunce (dbi-users@perl.org)',
                        'DIR' => [],
                        'DEFINE' => ' -DUTF8_SUPPORT -DNEW_OCI_INIT -DORA_OCI_VERSION=\\"9.2.0.1\\"',
                        'dynamic_lib' => {
                                           'OTHERLDFLAGS' => ' -g'
                                         },
                        'dist' => {
                                    'DIST_DEFAULT' => 'clean distcheck disttest tardist',
                                    'COMPRESS' => 'gzip -v9',
                                    'PREOP' => '$(MAKE) -f Makefile.old distdir',
                                    'SUFFIX' => 'gz'
                                  },
                        'OBJECT' => '$(O_FILES)',
                        'clean' => {
                                     'FILES' => 'xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def ora_explain mk.pm DBD_ORA_OBJ.*'
                                   },
                        'EXE_FILES' => [
                                         'ora_explain'
                                       ],
                        'ABSTRACT_FROM' => 'Oracle.pm',
                        'VERSION_FROM' => 'Oracle.pm',
                        'PREREQ_PM' => {
                                         'DBI' => 0
                                       }
                      };
$dbd_oracle_mm_self = bless( {
                               'MM_Win32_VERSION' => '1.12',
                               'BSLOADLIBS' => '',
                               'ECHO_N' => '$(ABSPERLRUN)  -e "print qq{@ARGV}"',
                               'BOOTDEP' => '',
                               'CCDLFLAGS' => ' ',
                               'LDDLFLAGS' => '-dll -nologo -nodefaultlib -debug -opt:ref,icf  -libpath:"C:\\Perl\\lib\\CORE"  -machine:x86',
                               'DESTINSTALLVENDORMAN3DIR' => '$(DESTDIR)$(INSTALLVENDORMAN3DIR)',
                               'LDLOADLIBS' => 'C:\\oracle\\ora92\\oci\\LIB\\MSVC\\OCI.lib "C:\\Program Files\\Microsoft Visual Studio .NET 2003\\Vc7\\lib\\oldnames.lib" "C:\\Program Files\\Microsoft Visual Studio .NET 2003\\Vc7\\lib\\kernel32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\user32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\gdi32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\winspool.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\comdlg32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\advapi32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\shell32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\ole32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\oleaut32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\netapi32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\uuid.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\ws2_32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\mpr.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\winmm.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\version.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\odbc32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\odbccp32.lib" "C:\\Program Files\\Microsoft Visual Studio .NET 2003\\Vc7\\lib\\msvcrt.lib"',
                               'INST_HTMLDIR' => 'blib\\html',
                               'PREOP' => '$(NOECHO) $(NOOP)',
                               'MACROSTART' => '',
                               'DESTINSTALLVENDORHTMLDIR' => '$(DESTDIR)$(INSTALLVENDORHTMLDIR)',
                               'XS_VERSION' => '1.18',
                               'MAKEMAKER' => 'C:/Perl/lib/ExtUtils/MakeMaker.pm',
                               'USEMAKEFILE' => '-f',
                               'RM_RF' => '$(ABSPERLRUN) -MExtUtils::Command -e rm_rf',
                               'PMLIBDIRS' => [
                                                'lib'
                                              ],
                               'INST_LIBDIR' => '$(INST_LIB)\\DBD',
                               'SITEARCHEXP' => 'C:\\Perl\\site\\lib',
                               'INST_MAN1DIR' => 'blib\\man1',
                               'MAN3EXT' => '3',
                               'XS' => {
                                         'Oracle.xs' => 'Oracle.c'
                                       },
                               'FULL_AR' => '',
                               'FULLPERL' => 'C:\\Perl\\bin\\perl.exe',
                               'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                               'CONFIG' => [
                                             'ar',
                                             'cc',
                                             'cccdlflags',
                                             'ccdlflags',
                                             'dlext',
                                             'dlsrc',
                                             'ld',
                                             'lddlflags',
                                             'ldflags',
                                             'libc',
                                             'lib_ext',
                                             'obj_ext',
                                             'osname',
                                             'osvers',
                                             'ranlib',
                                             'sitelibexp',
                                             'sitearchexp',
                                             'so',
                                             'exe_ext',
                                             'full_ar',
                                             'vendorarchexp',
                                             'vendorlibexp'
                                           ],
                               'DESTDIR' => '',
                               'INSTALLSITEHTMLDIR' => 'C:\\Perl\\html',
                               'MAN1PODS' => {
                                               'ora_explain' => '$(INST_MAN1DIR)\\ora_explain.$(MAN1EXT)'
                                             },
                               'INSTALLSITEBIN' => 'C:\\Perl\\bin',
                               'CHMOD' => '$(ABSPERLRUN) -MExtUtils::Command -e chmod',
                               'DESTINSTALLVENDORLIB' => '$(DESTDIR)$(INSTALLVENDORLIB)',
                               'OBJ_EXT' => '.obj',
                               'C' => [
                                        'Oracle.c',
                                        'dbdimp.c',
                                        'oci8.c'
                                      ],
                               'EXE_FILES' => $dbd_oracle_mm_opts->{'EXE_FILES'},
                               'TARFLAGS' => 'cvf',
                               'PERL_INC' => 'C:\\Perl\\lib\\CORE',
                               'HAS_LINK_CODE' => 1,
                               'INSTALLPRIVLIB' => 'C:\\Perl\\lib',
                               'SITELIBEXP' => 'C:\\Perl\\site\\lib',
                               'DESTINSTALLPRIVLIB' => '$(DESTDIR)$(INSTALLPRIVLIB)',
                               'VENDORLIBEXP' => '',
                               'FULLEXT' => 'DBD\\Oracle',
                               'DEFINE' => ' -DUTF8_SUPPORT -DNEW_OCI_INIT -DORA_OCI_VERSION=\\"9.2.0.1\\"',
                               'dynamic_lib' => $dbd_oracle_mm_opts->{'dynamic_lib'},
                               'MAKEFILE' => 'Makefile',
                               'PL_FILES' => {
                                               'ora_explain.PL' => 'ora_explain'
                                             },
                               'VENDORARCHEXP' => '',
                               'MM_VERSION' => '6.30',
                               'INSTALLSCRIPT' => 'C:\\Perl\\bin',
                               'CC' => 'cl',
                               'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                               'DLEXT' => 'dll',
                               'EQUALIZE_TIMESTAMP' => '$(ABSPERLRUN) "-MExtUtils::Command" -e eqtime',
                               'XS_VERSION_MACRO' => 'XS_VERSION',
                               'VERBINST' => 0,
                               'TAR' => 'tar',
                               'ABSPERL' => '$(PERL)',
                               'DESTINSTALLARCHLIB' => '$(DESTDIR)$(INSTALLARCHLIB)',
                               'INST_STATIC' => '$(INST_ARCHAUTODIR)\\$(BASEEXT)$(LIB_EXT)',
                               'DISTVNAME' => 'DBD-Oracle-1.18',
                               'ABSTRACT_FROM' => 'Oracle.pm',
                               'DESTINSTALLSCRIPT' => '$(DESTDIR)$(INSTALLSCRIPT)',
                               'INST_AUTODIR' => '$(INST_LIB)\\auto\\$(FULLEXT)',
                               'RESULT' => [
                                             '# This Makefile is for the DBD::Oracle extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.30 (Revision: Revision: 4535 ) from the contents of
# Makefile.PL. Don\'t edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#
#   MakeMaker Parameters:
',
                                             '#     ABSTRACT_FROM => q[Oracle.pm]',
                                             '#     AUTHOR => q[Tim Bunce (dbi-users@perl.org)]',
                                             '#     DEFINE => q[ -DUTF8_SUPPORT -DNEW_OCI_INIT -DORA_OCI_VERSION=\\"9.2.0.1\\"]',
                                             '#     DIR => []',
                                             '#     EXE_FILES => [q[ora_explain]]',
                                             '#     INC => q[-IC:/oracle/ora92/oci/include -IC:/oracle/ora92/rdbms/demo -IC:/Perl/site/lib/auto/DBI/]',
                                             '#     LIBS => [q[-LC:/oracle/ora92/oci/LIB/MSVC OCI]]',
                                             '#     NAME => q[DBD::Oracle]',
                                             '#     OBJECT => q[$(O_FILES)]',
                                             '#     PREREQ_PM => { DBI=>q[0] }',
                                             '#     VERSION_FROM => q[Oracle.pm]',
                                             '#     clean => { FILES=>q[xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def ora_explain mk.pm DBD_ORA_OBJ.*] }',
                                             '#     dist => { DIST_DEFAULT=>q[clean distcheck disttest tardist], COMPRESS=>q[gzip -v9], PREOP=>q[$(MAKE) -f Makefile.old distdir], SUFFIX=>q[gz] }',
                                             '#     dynamic_lib => { OTHERLDFLAGS=>q[ -g] }',
                                             '
# --- MakeMaker post_initialize section:'
                                           ],
                               'FULLPERLRUNINST' => '$(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'MAP_TARGET' => 'perl',
                               'INSTALLMAN3DIR' => 'C:\\Perl\\man\\man3',
                               'PERLPREFIX' => 'C:\\Perl',
                               'AUTHOR' => 'Tim Bunce (dbi-users@perl.org)',
                               'INC' => '-IC:/oracle/ora92/oci/include -IC:/oracle/ora92/rdbms/demo -IC:/Perl/site/lib/auto/DBI/',
                               'LDFLAGS' => '-nologo -nodefaultlib -debug -opt:ref,icf  -libpath:"C:\\Perl\\lib\\CORE"  -machine:x86',
                               'INSTALLVENDORHTMLDIR' => 'C:\\Perl\\html',
                               'dist' => $dbd_oracle_mm_opts->{'dist'},
                               'INSTALLVENDORMAN1DIR' => '',
                               'MAKEFILE_OLD' => 'Makefile.old',
                               'H' => [
                                        'Oracle.h',
                                        'dbdimp.h',
                                        'dbivport.h',
                                        'ocitrace.h'
                                      ],
                               'PERLRUNINST' => '$(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'CI' => 'ci -u',
                               'DESTINSTALLBIN' => '$(DESTDIR)$(INSTALLBIN)',
                               'DESTINSTALLVENDORMAN1DIR' => '$(DESTDIR)$(INSTALLVENDORMAN1DIR)',
                               'INST_ARCHLIBDIR' => '$(INST_ARCHLIB)\\DBD',
                               'OBJECT' => '$(O_FILES)',
                               'NAME_SYM' => 'DBD_Oracle',
                               'RANLIB' => 'rem',
                               'DIRFILESEP' => '^\\',
                               'POSTOP' => '$(NOECHO) $(NOOP)',
                               'INSTALLVENDORBIN' => '',
                               'COMPRESS' => 'gzip --best',
                               'SUFFIX' => '.gz',
                               'MAN1EXT' => '1',
                               'PERL_LIB' => 'C:\\Perl\\lib',
                               'ECHO' => '$(ABSPERLRUN) -l -e "print qq{@ARGV}"',
                               'EXPORT_LIST' => '$(BASEEXT).def',
                               'INST_BOOT' => '$(INST_ARCHAUTODIR)\\$(BASEEXT).bs',
                               'MV' => '$(ABSPERLRUN) -MExtUtils::Command -e mv',
                               'OSVERS' => '5.0',
                               'LD_RUN_PATH' => '',
                               'MKPATH' => '$(ABSPERLRUN) "-MExtUtils::Command" -e mkpath',
                               'DESTINSTALLMAN1DIR' => '$(DESTDIR)$(INSTALLMAN1DIR)',
                               'OSNAME' => 'MSWin32',
                               'AR' => 'lib',
                               'O_FILES' => [
                                              'Oracle.obj',
                                              'dbdimp.obj',
                                              'oci8.obj'
                                            ],
                               'FIXIN' => 'pl2bat.bat',
                               'DIST_DEFAULT' => 'tardist',
                               'SKIPHASH' => {},
                               'NOOP' => 'rem',
                               'PERL_ARCHLIB' => 'C:\\Perl\\lib',
                               'VERSION_SYM' => '1_18',
                               'VERSION_MACRO' => 'VERSION',
                               'WARN_IF_OLD_PACKLIST' => '$(ABSPERLRUN) "-MExtUtils::Command::MM" -e warn_if_old_packlist',
                               'MM_REVISION' => 'Revision: 4535 ',
                               'RM_F' => '$(ABSPERLRUN) -MExtUtils::Command -e rm_f',
                               'LIBC' => 'msvcrt.lib',
                               'UNINST' => 0,
                               'PERLRUN' => '$(PERL)',
                               'LINKTYPE' => 'dynamic',
                               'INSTALLVENDORLIB' => '',
                               'DEV_NULL' => '> NUL',
                               'DLSRC' => 'dl_win32.xs',
                               'INST_ARCHAUTODIR' => '$(INST_ARCHLIB)\\auto\\$(FULLEXT)',
                               'DESTINSTALLSITEBIN' => '$(DESTDIR)$(INSTALLSITEBIN)',
                               'MACROEND' => '',
                               'ARGS' => {
                                           'NAME' => 'DBD::Oracle',
                                           'INC' => '-IC:/oracle/ora92/oci/include -IC:/oracle/ora92/rdbms/demo -IC:/Perl/site/lib/auto/DBI/',
                                           'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                                           'AUTHOR' => 'Tim Bunce (dbi-users@perl.org)',
                                           'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                                           'DEFINE' => ' -DUTF8_SUPPORT -DNEW_OCI_INIT -DORA_OCI_VERSION=\\"9.2.0.1\\"',
                                           'dynamic_lib' => $dbd_oracle_mm_opts->{'dynamic_lib'},
                                           'dist' => $dbd_oracle_mm_opts->{'dist'},
                                           'OBJECT' => '$(O_FILES)',
                                           'clean' => $dbd_oracle_mm_opts->{'clean'},
                                           'EXE_FILES' => $dbd_oracle_mm_opts->{'EXE_FILES'},
                                           'ABSTRACT_FROM' => 'Oracle.pm',
                                           'VERSION_FROM' => 'Oracle.pm',
                                           'PREREQ_PM' => $dbd_oracle_mm_opts->{'PREREQ_PM'}
                                         },
                               'CP' => '$(ABSPERLRUN) -MExtUtils::Command -e cp',
                               'DEFINE_VERSION' => '-D$(VERSION_MACRO)=\\"$(VERSION)\\"',
                               'PREREQ_PM' => $dbd_oracle_mm_opts->{'PREREQ_PM'},
                               'DESTINSTALLSITELIB' => '$(DESTDIR)$(INSTALLSITELIB)',
                               'INST_LIB' => 'blib\\lib',
                               'INST_DYNAMIC' => '$(INST_ARCHAUTODIR)\\$(DLBASE).$(DLEXT)',
                               'FULLPERLRUN' => '$(FULLPERL)',
                               'INSTALLSITEMAN1DIR' => '$(INSTALLMAN1DIR)',
                               'DESTINSTALLSITEMAN3DIR' => '$(DESTDIR)$(INSTALLSITEMAN3DIR)',
                               'MOD_INSTALL' => '$(ABSPERLRUN) -MExtUtils::Install -e "install({@ARGV}, \'$(VERBINST)\', 0, \'$(UNINST)\');"',
                               'DLBASE' => '$(BASEEXT)',
                               'INST_MAN3DIR' => 'blib\\man3',
                               'CCCDLFLAGS' => ' ',
                               'INSTALLSITEARCH' => 'C:\\Perl\\site\\lib',
                               'XS_DEFINE_VERSION' => '-D$(XS_VERSION_MACRO)=\\"$(XS_VERSION)\\"',
                               'SHAR' => 'shar',
                               'PERLMAINCC' => '$(CC)',
                               'RCS_LABEL' => 'rcs -Nv$(VERSION_SYM): -q',
                               'NAME' => 'DBD::Oracle',
                               'PARENT_NAME' => 'DBD',
                               'INSTALLSITELIB' => 'C:\\Perl\\site\\lib',
                               'MAKE_APERL_FILE' => 'Makefile.aperl',
                               'ZIP' => 'zip',
                               'VERSION_FROM' => 'Oracle.pm',
                               'SITEPREFIX' => 'C:\\Perl\\site',
                               'TO_UNIX' => '$(NOECHO) $(NOOP)',
                               'PERL' => 'C:\\Perl\\bin\\perl.exe',
                               'DESTINSTALLVENDORARCH' => '$(DESTDIR)$(INSTALLVENDORARCH)',
                               'NOECHO' => '@',
                               'DESTINSTALLVENDORBIN' => '$(DESTDIR)$(INSTALLVENDORBIN)',
                               'DESTINSTALLHTMLDIR' => '$(DESTDIR)$(INSTALLHTMLDIR)',
                               'PERM_RW' => 644,
                               'UMASK_NULL' => 'umask 0',
                               'DOC_INSTALL' => '$(ABSPERLRUN) "-MExtUtils::Command::MM" -e perllocal_install',
                               'TOUCH' => '$(ABSPERLRUN) -MExtUtils::Command -e touch',
                               'LD' => 'link',
                               'PERL_SRC' => undef,
                               'DESTINSTALLMAN3DIR' => '$(DESTDIR)$(INSTALLMAN3DIR)',
                               'ZIPFLAGS' => '-r',
                               'DISTNAME' => 'DBD-Oracle',
                               'INST_BIN' => 'blib\\bin',
                               'FIRST_MAKEFILE' => 'Makefile',
                               'VENDORPREFIX' => '',
                               'LDFROM' => '$(OBJECT)',
                               'clean' => $dbd_oracle_mm_opts->{'clean'},
                               'PREFIX' => '$(SITEPREFIX)',
                               'INSTALLDIRS' => 'site',
                               'INST_ARCHLIB' => 'blib\\arch',
                               'INSTALLHTMLDIR' => 'C:\\Perl\\html',
                               'PERL_ARCHIVE' => '$(PERL_INC)\\perl58.lib',
                               'INSTALLVENDORARCH' => '',
                               'INSTALLBIN' => 'C:\\Perl\\bin',
                               'DESTINSTALLSITEMAN1DIR' => '$(DESTDIR)$(INSTALLSITEMAN1DIR)',
                               'INSTALLSITEMAN3DIR' => '$(INSTALLMAN3DIR)',
                               'PERL_ARCHIVE_AFTER' => '',
                               'MAN3PODS' => {
                                               'Oracle.pm' => '$(INST_MAN3DIR)\\DBD\\Oracle.$(MAN3EXT)',
                                               'Oraperl.pm' => '$(INST_MAN3DIR)\\DBD\\Oraperl.$(MAN3EXT)'
                                             },
                               'LIBPERL_A' => 'libperl.lib',
                               'INSTALLARCHLIB' => 'C:\\Perl\\lib',
                               'LIB_EXT' => '.lib',
                               'DESTINSTALLSITEHTMLDIR' => '$(DESTDIR)$(INSTALLSITEHTMLDIR)',
                               'AR_STATIC_ARGS' => 'cr',
                               'INSTALLVENDORMAN3DIR' => '',
                               'EXE_EXT' => '.exe',
                               'EXTRALIBS' => 'C:\\oracle\\ora92\\oci\\LIB\\MSVC\\OCI.lib "C:\\Program Files\\Microsoft Visual Studio .NET 2003\\Vc7\\lib\\oldnames.lib" "C:\\Program Files\\Microsoft Visual Studio .NET 2003\\Vc7\\lib\\kernel32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\user32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\gdi32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\winspool.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\comdlg32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\advapi32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\shell32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\ole32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\oleaut32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\netapi32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\uuid.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\ws2_32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\mpr.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\winmm.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\version.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\odbc32.lib" "C:\\Program Files\\Microsoft Platform SDK\\Lib\\odbccp32.lib" "C:\\Program Files\\Microsoft Visual Studio .NET 2003\\Vc7\\lib\\msvcrt.lib"',
                               'PERM_RWX' => 755,
                               'DESTINSTALLSITEARCH' => '$(DESTDIR)$(INSTALLSITEARCH)',
                               'ABSPERLRUN' => '$(ABSPERL)',
                               'BASEEXT' => 'Oracle',
                               'TEST_F' => '$(ABSPERLRUN) -MExtUtils::Command -e test_f',
                               'PM' => {
                                         'Oracle.pm' => '$(INST_LIB)\\DBD\\Oracle.pm',
                                         'utf8_err.pl' => '$(INST_LIB)\\DBD\\utf8_err.pl',
                                         'oraperl.ph' => '$(INST_LIB)/oraperl.ph',
                                         'mkta.pl' => '$(INST_LIB)\\DBD\\mkta.pl',
                                         'Oraperl.pm' => '$(INST_LIB)/Oraperl.pm',
                                         'lib/DBD/Oracle/GetInfo.pm' => 'blib\\lib\\DBD\\Oracle\\GetInfo.pm',
                                         'mk.pm' => '$(INST_LIB)\\DBD\\mk.pm'
                                       },
                               'ABSPERLRUNINST' => '$(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'PERL_CORE' => 0,
                               'INSTALLMAN1DIR' => 'C:\\Perl\\man\\man1',
                               'SO' => 'dll',
                               'VERSION' => '1.18',
                               'DIST_CP' => 'best',
                               'INST_SCRIPT' => 'blib\\script',
                               'UNINSTALL' => '$(ABSPERLRUN) "-MExtUtils::Command::MM" -e uninstall'
                             }, 'PACK001' );
