From SRS0=KVnF=PW=perl.org=dbi-users-return-25388-Tim.Bunce=pobox.com@bounce2.pobox.com  Fri Jan  7 16:11:33 2005
Received: from localhost (localhost [IPv6:::1])
	by dansat.data-plan.com (8.13.1/8.13.1) with ESMTP id j07GAqfa044155
	for <timbo@localhost>; Fri, 7 Jan 2005 16:11:32 GMT
	(envelope-from SRS0=KVnF=PW=perl.org=dbi-users-return-25388-Tim.Bunce=pobox.com@bounce2.pobox.com)
Received: from pop3.mail.demon.net [194.217.242.253]
	by localhost with POP3 (fetchmail-6.2.5)
	for timbo@localhost (single-drop); Fri, 07 Jan 2005 16:11:32 +0000 (GMT)
Received: from punt-3.mail.demon.net by mailstore
	for pobox@data-plan.com id 1CmvQB-0003Po-Kf;
	Fri, 07 Jan 2005 14:48:59 +0000
Received: from [194.217.242.77] (helo=anchor-hub.mail.demon.net)
	by punt-3.mail.demon.net with esmtp id 1CmvQB-0003Po-Kf
	for pobox@data-plan.com; Fri, 07 Jan 2005 14:48:59 +0000
Received: from [208.58.1.193] (helo=boggle.pobox.com)
	by anchor-hub.mail.demon.net with esmtp id 1CmvQA-0002zW-VM
	for pobox@data-plan.com; Fri, 07 Jan 2005 14:48:59 +0000
Received: from boggle.pobox.com (localhost [127.0.0.1])
	by boggle.pobox.com (Postfix) with ESMTP id 49778102ACC;
	Fri,  7 Jan 2005 09:48:58 -0500 (EST)
Delivered-To: tim.bunce@pobox.com
Received: from boggle (localhost [127.0.0.1])
	by boggle.pobox.com (Postfix) with ESMTP id 384E5FF808
	for <tim.bunce@pobox.com.13888548.001.icgmh>; Fri,  7 Jan 2005 09:48:58 -0500 (EST)
Received-SPF: pass (boggle.pobox.com: domain of dbi-users-return-25388-Tim.Bunce=pobox.com@perl.org designates 63.251.223.186 as permitted sender)
X-SPF-Guess: pass (seems reasonable for dbi-users-return-25388-Tim.Bunce=pobox.com@perl.org to mail through 63.251.223.186)
X-Pobox-Antispam: dnsbl/blackholes.five-ten-sg.com returned DENY: for 63.251.223.186(x6.develooper.com)
Received: from lists.develooper.com (x6.develooper.com [63.251.223.186])
	by boggle.pobox.com (Postfix) with SMTP id A74B8F4090
	for <Tim.Bunce@pobox.com>; Fri,  7 Jan 2005 09:48:57 -0500 (EST)
Received: (qmail 2690 invoked by uid 514); 7 Jan 2005 14:48:56 -0000
Mailing-List: contact dbi-users-help@perl.org; run by ezmlm
Precedence: bulk
List-Post: <mailto:dbi-users@perl.org>
List-Help: <mailto:dbi-users-help@perl.org>
List-Unsubscribe: <mailto:dbi-users-unsubscribe@perl.org>
List-Subscribe: <mailto:dbi-users-subscribe@perl.org>
Delivered-To: mailing list dbi-users@perl.org
Received: (qmail 2622 invoked from network); 7 Jan 2005 14:48:55 -0000
Received: from x1.develooper.com (63.251.223.170)
  by lists.develooper.com with SMTP; 7 Jan 2005 14:48:55 -0000
Received: (qmail 13078 invoked by uid 225); 7 Jan 2005 14:48:54 -0000
Delivered-To: dbi-users@perl.org
Received: (qmail 13048 invoked by alias); 7 Jan 2005 14:48:51 -0000
X-Spam-Status: No, hits=-4.6 required=8.0
	tests=BAYES_00,HTML_MESSAGE,NO_REAL_NAME
X-Spam-Check-By: la.mx.develooper.com
Received-SPF: neutral (x1.develooper.com: local policy)
Received: from outmx020.isp.belgacom.be (HELO outmx020.isp.belgacom.be) (195.238.2.201)
  by la.mx.develooper.com (qpsmtpd/0.28) with ESMTP; Fri, 07 Jan 2005 06:48:38 -0800
Received: from outmx020.isp.belgacom.be (localhost [127.0.0.1])
        by outmx020.isp.belgacom.be (8.12.11/8.12.11/Skynet-OUT-2.22) with ESMTP id j07EmOgS020070
        for <dbi-users@perl.org>; Fri, 7 Jan 2005 15:48:24 +0100
        (envelope-from <Bjorn.Naessens@roularta.be>)
Received: from relaytwo.roularta.be (smtprelaytwo.roularta.be [194.78.177.23])
        by outmx020.isp.belgacom.be (8.12.11/8.12.11/Skynet-OUT-2.22) with ESMTP id j07EmMDA020034
        for <dbi-users@perl.org>; Fri, 7 Jan 2005 15:48:22 +0100
        (envelope-from <Bjorn.Naessens@roularta.be>)
Received: from rmgexch01.RMG.be ([89.0.35.150]) by roesfront3.RMG.be with Microsoft SMTPSVC(5.0.2195.6713);
	 Fri, 7 Jan 2005 15:47:50 +0100
X-MimeOLE: Produced By Microsoft Exchange V6.5.7226.0
Content-class: urn:content-classes:message
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----_=_NextPart_001_01C4F4C7.EE810087"
Subject: A succesfull 64-bit build of Perl-DBI-DBD:Oracle on IBM AIX 5.2 
Date: Fri, 7 Jan 2005 15:48:21 +0100
Message-ID: <E2D46872D48E224998CD1EAE52A83656690E2E@rmgexch01.rmg.be>
X-MS-Has-Attach: 
X-MS-TNEF-Correlator: 
Thread-Topic: A succesfull 64-bit build of Perl-DBI-DBD:Oracle on IBM AIX 5.2 
Thread-Index: AcT0x+Y4G1R3vbX6Rh+QdPyNy/10eQ==
From: <Bjorn.Naessens@roularta.be>
To: <dbi-users@perl.org>
X-OriginalArrivalTime: 07 Jan 2005 14:47:50.0598 (UTC) FILETIME=[DC5D2E60:01C4F4C7]
Status: RO
Content-Length: 1678
Lines: 62

------_=_NextPart_001_01C4F4C7.EE810087
Content-Type: text/plain;
	charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

Hi,=20
=20
I finally succeeded in installing a 64bit build of Perl and its modules
for Oracle 64-bit. We were running in 32bit but integrating Proc and
cobols in our perl scripts only worked when we changed environments to
64bit causing problems for the oracle connections in perl. It's nothing
special, no editing of makefiles ... I can't believe I lost so much time
on this one ;) ( Now that I look back to my problems, they were probably
caused by using a wrong perl build for compiling the modules, Aix has
its default perl now under /bin.. stupid me )=20
=20
perl 5.8.6 64bit
----------------
./Configure -de -Dcc=3Dgcc -Duse64bitall=20
make
make test
make install
=20
DBI 1.46
--------
!!Make sure you are using the newly installed perl!!
 check with perl -v it should show :=20
 This is perl, v5.8.6 built for aix-64all
perl Makefile.PL
make
make test
make install=20
=20
DBD-Oracle 1.16
---------------
!!Use correct perl like above mentioned!!=20
export ORACLE_HOME=3D<path to oraclehome>=20
export LIBPATH=3D$ORACLE_HOME/lib
export LD_LIBRARY_PATH=3D$ORACLE_HOME/lib
=20
perl Makefile.PL=20
make
make test ( some test may still fail, I had 85% success on tests )=20
make install=20
=20
Test
----=20
=20
test with :=20
 use DBI;
 $dbh=3DDBI->connect("dbi:Oracle:<SID>","system","manager")|| die
$DBI::errstr;
 $stmt=3D$dbh->prepare("select * from tab");
 $rc=3D$stmt->execute()  || die $DBI::errstr;
 while (my($record)=3D$stmt->fetchrow())
 {
  print $record;
 }
=20
Happy 64-bit perling ;)=20

------_=_NextPart_001_01C4F4C7.EE810087--

